### ISSUE TITLE
how do i activate the theme?

### ISSUE THREAD

**Issue by el3ctron** [jonnay/org-beautify-theme#1]
if i do load-theme command, org-beautify-theme doesnt appear.. how do i activate the theme?

**Comment by jonnay** [comment]
Hmm.. That should be all that is needed.  

Did you install it from MELPA?

What happens when you do `M-x describe-theme org-beautify`?

**Comment by el3ctron** [comment]
installed from melpa.

when i do M-x describe-theme org-beautify, appears:

```
org-beautify is a custom theme.
It is not loaded.

Documentation:
No documentation available.

You can customize this theme.

```

**Comment by jonnay** [comment]
Okay, that's weird.

Once you do the describe theme can you load it with M-x load-theme?

I am pretty busy with work lately, so I don't know when I can dig into this, but I'll do my best!

**Comment by sergiodiezdepedro** [comment]
Hi jonnay. I've got same problem that @el3ctron described: Theme instaled from MELPA.

Doing M-x describe-theme org-beautify: 

```
org-beautify is a custom theme.
It is not loaded.

Documentation:
No documentation available.

You can customize this theme

```

**Comment by vitaminless** [comment]
I did following in my .emacs:

```
(add-to-list 'custom-theme-load-path
         (concat
          "~/.emacs.d/elpa/"
          (elt (directory-files "~/.emacs.d/elpa/" nil "org-beautify-theme-[0-9].*") 0)))
(add-hook 'org-mode-hook (lambda () (load-theme 'org-beautify)))
```

**Comment by sergiodiezdepedro** [comment]
Many thx for the tip, @vitaminless. Worked fine here. 

Whitout the last line (ad-hook ...) you may load the theme with M-x load theme RET org-beautify if you want. 

So, this issue seems to be a path problem, or somethign like that. I'm sorry, but I don't know lisp

Greetings

**Comment by jonnay** [comment]
Fixed here: https://github.com/jonnay/org-beautify-theme/pull/2

**Comment by jonnay** [comment]
Thanks @vitaminless for helping out!

**Comment by jonnay** [comment]
This should be fixed now.
