### ISSUE TITLE
error: Window system is not in use or not initialized

### ISSUE THREAD

**Issue by shackra** [jonnay/org-beautify-theme#9]
I'm experiencing the bug reported in https://github.com/bbatsov/prelude/issues/1093

Turning off this package fixes it.

**Comment by jonnay** [comment]
Heh.

"Doctor Doctor... it hurts when I do this!"  "Well Don't do it!"

you could try:

```
(when window-system
  ... load theme here ... )
```

But otherwise I don't think this is a bug with org-beautify-theme.  It's whole raison d'etre is to make org mode look nice on a window system.  Loading a theme in daemon mode is your problem.
